[package]
name = "git_command_line"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html




[dependencies]
command_macro = {path= "./command_macro"} 
